import enum


class ErrorStatus(str, enum.Enum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
